name: Pre-commit Checks

on:
  push:
    branches:
      - main
    paths:
      - "**/*.{js,jsx,ts,tsx,json,css,scss,md}"
  pull_request:
    paths:
      - "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Run Prettier
        run: yarn format-check
